### ISSUE TITLE
Matched quote/paren/brace/braket deletion

### ISSUE THREAD

**Issue by daphil19** [jedmao/vscode-tabsanity#17]
Tabsanity appears to break the ability to delete adjacent, matching pair of characters like:
```
[]
()
{}
''
```
etc.

Example (in `.js` file)
![peek 2018-02-09 15-13](https://user-images.githubusercontent.com/12862688/36048038-e938ecda-0dab-11e8-8602-a9b550a3bc9b.gif)

**Comment by jednano** [comment]
Hmm, that looks like perhaps a tough one to fix. Willing to accept PRs, but I don't think I'll be going down this road myself. Thanks for logging the issue!

**Comment by peterctl** [comment]
I did a small test on my local computer. It seems that deleting the backspace functionality solves this issue. Also, VS Code has the functionality to delete whitespace until the next tab stop when backspace is pressed, so it seems to me that including such functionality in this extension is redundant.

I think this was added to the editor core recently, so it shouldn't be needed anymore. I can do a PR in a week or two since I am on finals week at my university. Please let me know if I'm missing something or if I should do the PR to remove the delete functionality from the extension.

**Comment by jednano** [comment]
@PeterCP I would greatly appreciate a PR. Thanks!

**Comment by jednano** [comment]
Published in v0.0.10. Thanks for the help!

**Comment by peterctl** [comment]
Thanks to you for making such an awesome and useful extension 😀 cheers!
